version: '3.3'

services:
  orc-hdfs-spark:
    image: jalves7/spark-scala-orc-processing:1.0-SNAPSHOT 
    hostname: orc-hdfs-spark
#    ports:
#     - target: 4040
#       published: 2840
#       protocol: tcp
#       mode: host
    environment:
     - ENABLE_INIT_DAEMON=false
    restart: always
#    deploy:
#      restart_policy:
#        condition: always
#      placement:
#        constraints:
#          - node.hostname == ebithp-c8
    networks:
     cm_project:
           aliases:
               - orc-hdfs-spark
networks:
     cm_project:
           external:
             name: jalves7
