version: '3.3'

services:
  ml-spark-realtime:
    image: jalves7/ml-spark-realtime:1.0-SNAPSHOT
    hostname: ml-spark-realtime
#    ports:
#     - target: 4040
#       published: 2340
#       protocol: tcp
#       mode: host
    environment:
     - ENABLE_INIT_DAEMON=false
    deploy:
      restart_policy:
        condition: none
      placement:
        constraints:
          - node.hostname == ebithp-c8
    networks:
     cm_project:
           aliases:
               - ml-spark-realtime
networks:
     cm_project:
           external:
             name: cm_project
