version: '3.3'

services:
  app-spark:
    image: jalves7/spark-scala-pivot-csv-data:1.0-SNAPSHOT
    hostname: app-spark
    ports:
     - target: 4040
       published: 2040
       protocol: tcp
       mode: host
    environment:
     - ENABLE_INIT_DAEMON=false
    deploy:
      placement:
        constraints:
          - node.hostname == ebithp-c8
    networks:
     mongodb_cm :
           aliases:
               - app-spark
networks:
     mongodb_cm:
           external:
             name: kafka-zookeeper
