version: '3.3'

services:
  mongo-kafka-spark:
    image: jalves7/mongo-scala-kafka-consumer:1.0-SNAPSHOT
    hostname: mongo-kafka-spark
#    ports:
#     - target: 4040
#       published: 2340
#       protocol: tcp
#       mode: host
    environment:
     - ENABLE_INIT_DAEMON=false
    restart: always 
#    deploy:
#      restart_policy:
#        condition: always
#      placement:
#        constraints:
#          - node.hostname == ebithp-c8
    networks:
     cm_project:
           aliases:
               - mongo-kafka-spark
networks:
     cm_project:
           external:
             name: cm_project
