version: "3.3"
services:
  spark-notebook-cm:
    image: apache/zeppelin:0.8.0
    hostname: spark-notebook-cm
    volumes:
      - /home/jalves7/git/docker-spark/spark-2.3.0-bin-hadoop2.7:/usr/lib/spark
      - /storage/st01/jalves7/docker/cm/hadoop/home-namenode:/usr/lib/hadoop
      - /home/jalves7/git/docker-spark/hive-conf:/etc/hive/conf
      - $PWD/notebook:/notebook
#    env_file:
#      - ./hadoop.env
#    ports:
#      - target: 8080
#        published: 9983
#        protocol: tcp
#        mode: host
#      - target: 4040
#        published: 2140
#        protocol: tcp
#        mode: host
    environment:
      - ZEPPELIN_NOTEBOOK_DIR='/notebook' 
#      - ZEPPELIN_CONF_DIR='/zeppelin/conf'
    deploy:
#      labels:
#        - traefik.backend=spark-notebook-cm
#        - traefik.enable=true
#        - traefik.basic.frontend.rule=Host:spark-notebook-cm.app-status
#       - traefik.basic.port=80
#        - traefik.protocol=https
#        - traefik.frontend.rule=Path:/note-app-status
#        - traefik.port=4040
#        - traefik.docker.network= kafka-zookeeper
#        - traefik.enable=true
#        - traefik.frontend.auth.basic=admin:$$apr1$$XxidROKt$$PsiupGOEnVO9BjzAMP7NJ0 
#        - traefik.backend=spark-notebook-cm
#        - traefik.backend.loadbalancer.sticky=true
#        - traefik.admin.frontend.rule=Host:spark-notebook-cm.app-note
#        - traefik.enable=true
#        - traefik.admin.port=

      placement:
        constraints:
          - node.hostname == ebithp-c8
    networks:
      cm_project:
            aliases:
                - spark-notebook-cm
networks:
     cm_project:
           external:
             name: cm_project

