version: '3.3'
services:
  spark-master-demo:
    image: bde2020/spark-master:2.3.0-hadoop2.7 
    hostname: spark-master-demo
    environment:
      - INIT_DAEMON_STEP=setup_spark
    volumes:
      - /storage/st04/jalves7/projects/circuit-meter/spark-hadoop-conf:/etc/hadoop
    deploy:
      placement:
        constraints:
          - node.hostname == ebithp-c8
    networks:
      cm_project:
           aliases:
               - spark-master-demo

  spark-worker-demo-1:
    image: bde2020/spark-worker:2.3.0-hadoop2.7
    hostname: spark-worker-demo-1
    depends_on:
      - spark-master-demo
    environment:
      - "SPARK_MASTER=spark://spark-master-demo:7077"
    volumes:
      - /storage/st04/jalves7/projects/circuit-meter/spark-hadoop-conf:/etc/hadoop
    deploy:
      placement:
        constraints:
          - node.hostname == ebithp-c8
    networks:
      cm_project:
            aliases:
                - spark-worker-demo-1


  spark-worker-demo-2:
    image: bde2020/spark-worker:2.3.0-hadoop2.7
    hostname: spark-worker-demo-2
    depends_on:
      - spark-master-demo
    environment:
      - "SPARK_MASTER=spark://spark-master-demo:7077"
    volumes:
      - /storage/st04/jalves7/projects/circuit-meter/spark-hadoop-conf:/etc/hadoop
    deploy:
      placement:
        constraints:
          - node.hostname == ebithp-c8
    networks:
      cm_project:
            aliases:
                - spark-worker-demo-2


  spark-worker-demo-3:
    image: bde2020/spark-worker:2.3.0-hadoop2.7
    hostname: spark-worker-demo-3
    depends_on:
      - spark-master-demo
    environment:
      - "SPARK_MASTER=spark://spark-master-demo:7077"
    volumes:
      - /storage/st04/jalves7/projects/circuit-meter/spark-hadoop-conf:/etc/hadoop
    deploy:
      placement:
        constraints:
          - node.hostname == ebithp-c8
    networks:
      cm_project:
            aliases:
                - spark-worker-demo-3


networks:
     cm_project:
           external:
             name: demo-aviation




  
