version: '3.3'

services:
  traffic-data-orc:
    image: jalves7/traffic-data-orc:1.0-SNAPSHOT 
    hostname: traffic-data-orc
#    ports:
#     - target: 4040
#       published: 2840
#       protocol: tcp
#       mode: host
    environment:
     - ENABLE_INIT_DAEMON=false
    restart: always
#    deploy:
#      restart_policy:
#        condition: always
#      placement:
#        constraints:
#          - node.hostname == ebithp-c8
    networks:
     cm_project:
           aliases:
               - traffic-data-orc
networks:
     cm_project:
           external:
             name: jalves7
