version: "3.3"

services:
  hive-server:
    image: bde2020/hive:2.3.2-postgresql-metastore
    hostname: hive-server
    env_file:
      - ./hadoop-hive.env
    environment:
      HIVE_CORE_CONF_javax_jdo_option_ConnectionURL: "jdbc:postgresql://hive-metastore/metastore"
      SERVICE_PRECONDITION: "hive-metastore:9083"
#    ports:
#      - target: 10000
#        published: 10015
#        protocol: tcp
#        mode: host
    deploy:
      placement:
        constraints:
          - node.hostname == ebithp-c8
    networks:
      cm_project:
          aliases:
              - hive-server
  

  hive-metastore:
    image: bde2020/hive:2.3.2-postgresql-metastore
    hostname: hive-metastore
    env_file:
      - ./hadoop-hive.env
    command: /opt/hive/bin/hive --service metastore
    environment:
      SERVICE_PRECONDITION: "hive-metastore-postgresql:5432"
    deploy:
      placement:
        constraints:
          - node.hostname == ebithp-c8
    networks:
      cm_project:
          aliases:
              - hive-metastore


  hive-metastore-postgresql:
    image: bde2020/hive-metastore-postgresql:2.3.0
    hostname: hive-metastore-postgresql
    deploy:
      placement:
        constraints:
          - node.hostname == ebithp-c8
    networks:
      cm_project:
          aliases:
              - hive-metastore-postgreesql
networks:
     cm_project:
           external:
             name: jalves7
