version: '3.3'
services:
  zookeeper-demo:
    image: 31z4/zookeeper
    hostname: zookeeper-demo
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888
      ZOO_PORT: 12181
    volumes:
       - /storage/st02/jalves7/projects/demo-aviation/zookeeper/data:/data
       - /storage/st02/jalves7/projects/demo-aviation/zookeeper/datalog:/datalog

    deploy:
      placement:
        constraints:
          - node.hostname == ebithp-c8
    networks:
        cm_project:
                  aliases:
                    -  zookeeper-demo

networks:
     cm_project:
           external:
            name: jalves7
